// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockAnalysis.Data;

#nullable disable

namespace StockAnalysis.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260407082418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("StockAnalysis.Models.DailyQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "TradeDate")
                        .IsUnique();

                    b.ToTable("DailyQuotes");
                });

            modelBuilder.Entity("StockAnalysis.Models.DailyScreenResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgVolume20")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MA20")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("ScreenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumeRatio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "ScreenDate")
                        .IsUnique();

                    b.ToTable("DailyScreenResults");
                });

            modelBuilder.Entity("StockAnalysis.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Market")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockAnalysis.Models.TechnicalIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AvgVolume20")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MA20")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MA5")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MA60")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "TradeDate")
                        .IsUnique();

                    b.ToTable("TechnicalIndicators");
                });

            modelBuilder.Entity("StockAnalysis.Models.DailyQuote", b =>
                {
                    b.HasOne("StockAnalysis.Models.Stock", "Stock")
                        .WithMany("DailyQuotes")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalysis.Models.DailyScreenResult", b =>
                {
                    b.HasOne("StockAnalysis.Models.Stock", "Stock")
                        .WithMany("DailyScreenResults")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalysis.Models.TechnicalIndicator", b =>
                {
                    b.HasOne("StockAnalysis.Models.Stock", "Stock")
                        .WithMany("TechnicalIndicators")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockAnalysis.Models.Stock", b =>
                {
                    b.Navigation("DailyQuotes");

                    b.Navigation("DailyScreenResults");

                    b.Navigation("TechnicalIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
